// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDRuLIZ44UMKpZ4FcXNXmZID4hb4DslRv8',
    appId: '1:541413319013:web:e31960b280365749ee418c',
    messagingSenderId: '541413319013',
    projectId: 'holocaust-ish-shalom',
    authDomain: 'holocaust-ish-shalom.firebaseapp.com',
    storageBucket: 'holocaust-ish-shalom.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDviYBroC4b-rw_UW8zjKM8A8mEi8ReEnY',
    appId: '1:541413319013:android:6a1a892bcf735d21ee418c',
    messagingSenderId: '541413319013',
    projectId: 'holocaust-ish-shalom',
    storageBucket: 'holocaust-ish-shalom.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_s-eWGEiJRzWRf4_s2rXKamUr9Hno3kQ',
    appId: '1:541413319013:ios:aa8d39cfe774c617ee418c',
    messagingSenderId: '541413319013',
    projectId: 'holocaust-ish-shalom',
    storageBucket: 'holocaust-ish-shalom.appspot.com',
    iosClientId: '541413319013-t00oibttbg8e7qoref91o928j1hkcfer.apps.googleusercontent.com',
    iosBundleId: 'com.example.holocaustIshShalom',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_s-eWGEiJRzWRf4_s2rXKamUr9Hno3kQ',
    appId: '1:541413319013:ios:aa8d39cfe774c617ee418c',
    messagingSenderId: '541413319013',
    projectId: 'holocaust-ish-shalom',
    storageBucket: 'holocaust-ish-shalom.appspot.com',
    iosClientId: '541413319013-t00oibttbg8e7qoref91o928j1hkcfer.apps.googleusercontent.com',
    iosBundleId: 'com.example.holocaustIshShalom',
  );
}
